version: "3.8"
services:
  nginx:
    container_name: nginx_prod
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:80
  backend:
    container_name: backend_prod
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
      target: production
  frontend:
    container_name: frontend_prod
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod
      target: production
