FROM node:alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

RUN npm install -g @nestjs/cli

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

CMD ["node", "dist/main"]