FROM node:alpine as development

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

RUN npm install -g @nestjs/cli

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start:dev"]